#!/usr/bin/env bash
# setup.sh — Bootstrap claude-config-template on Linux, macOS, or WSL
# Usage: bash setup.sh [--non-interactive] [--help]

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
DATE="$(date '+%Y-%m-%d')"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

NON_INTERACTIVE=false

for arg in "$@"; do
  case "$arg" in
    --non-interactive) NON_INTERACTIVE=true ;;
    --help)
      cat <<'EOF'
Usage: bash setup.sh [--non-interactive] [--help]

Bootstraps the claude-config-template system on Linux, macOS, or WSL.

Flags:
  --non-interactive   Skip all prompts; use env vars or defaults
  --help              Show this message

Environment variables (non-interactive mode):
  CLAUDE_USER_NAME        Your full name
  CLAUDE_USER_ROLE        Your role or title
  CLAUDE_USER_BACKGROUND  Brief background description
  CLAUDE_USER_STYLE       Preferred communication style
  CLAUDE_MACHINE_ID       Machine identifier (default: hostname)
  CLAUDE_GITHUB_PAT       GitHub PAT for MCP setup (optional)
EOF
      exit 0 ;;
    *) echo -e "${RED}Unknown flag: $arg${RESET}" >&2; exit 1 ;;
  esac
done

step() { echo -e "\n${BOLD}${BLUE}Step $1${RESET} — $2"; }
ok()   { echo -e "  ${GREEN}+${RESET} $1"; }
warn() { echo -e "  ${YELLOW}!${RESET} $1"; }
die()  { echo -e "\n${RED}Error:${RESET} $1" >&2; exit 1; }

prompt() {
  # prompt <var_name> <label> <default>
  local var="$1" label="$2" default="$3"
  if [[ "$NON_INTERACTIVE" == true ]]; then
    printf -v "$var" '%s' "${!var:-$default}"
  else
    local answer
    read -r -p "  $label [${default}]: " answer
    printf -v "$var" '%s' "${answer:-$default}"
  fi
}

backup_if_exists() {
  local target="$1"
  if [[ -e "$target" || -L "$target" ]]; then
    mv "$target" "${target}.bak.${DATE}"
    warn "Backed up $(basename "$target") -> $(basename "$target").bak.${DATE}"
  fi
}

cmd_info() {
  # Returns "path | version" or "not found"
  local path; path="$(command -v "$1" 2>/dev/null)" || { echo "not found"; return; }
  local ver; ver="$("$1" --version 2>&1 | grep -oP '[\d]+\.[\d]+[\.\d]*' | head -1 || true)"
  echo "${path} | ${ver:-unknown}"
}

# ---------------------------------------------------------------------------
# Step 1 — Detect platform
# ---------------------------------------------------------------------------
step "1/6" "Detecting platform"

PLATFORM="linux"
[[ "$OSTYPE" == "darwin"* ]] && PLATFORM="macos"
grep -qi microsoft /proc/version 2>/dev/null && PLATFORM="wsl"
ok "Platform: ${PLATFORM}"

# ---------------------------------------------------------------------------
# Step 2 — Check prerequisites
# ---------------------------------------------------------------------------
step "2/6" "Checking prerequisites"

command -v git &>/dev/null || die "git is not installed. Please install git first."
ok "git: $(command -v git)"

[[ -d "$CLAUDE_DIR" ]] || mkdir -p "$CLAUDE_DIR" && ok "Config dir: ${CLAUDE_DIR}"
mkdir -p "$CLAUDE_DIR"/{foundation,domains,reference,hooks}

# ---------------------------------------------------------------------------
# Step 3 — User profile
# ---------------------------------------------------------------------------
step "3/6" "User profile setup"

PROFILE_FILE="$REPO_DIR/global/foundation/user-profile.md"

if [[ "$NON_INTERACTIVE" == true && -f "$PROFILE_FILE" ]]; then
  warn "Keeping existing user-profile.md (non-interactive)"
else
  CLAUDE_USER_NAME="${CLAUDE_USER_NAME:-}"
  CLAUDE_USER_ROLE="${CLAUDE_USER_ROLE:-}"
  CLAUDE_USER_BACKGROUND="${CLAUDE_USER_BACKGROUND:-}"
  CLAUDE_USER_STYLE="${CLAUDE_USER_STYLE:-}"

  prompt CLAUDE_USER_NAME       "Your full name"               "User"
  prompt CLAUDE_USER_ROLE       "Your role or title"           "Developer"
  prompt CLAUDE_USER_BACKGROUND "Brief background (1 line)"    "Software developer"
  prompt CLAUDE_USER_STYLE      "Preferred communication style" "Direct and technical"

  mkdir -p "$(dirname "$PROFILE_FILE")"
  cat > "$PROFILE_FILE" <<EOF
# User Profile

## Identity
- **Name:** ${CLAUDE_USER_NAME}
- **Role:** ${CLAUDE_USER_ROLE}

## Background
${CLAUDE_USER_BACKGROUND}

## Communication Style
${CLAUDE_USER_STYLE}

## Notes
_Auto-generated by setup.sh on ${DATE}. Edit freely._
EOF
  ok "Wrote global/foundation/user-profile.md"
fi

# ---------------------------------------------------------------------------
# Step 4 — Machine catalog
# ---------------------------------------------------------------------------
step "4/6" "Machine catalog"

CLAUDE_MACHINE_ID="${CLAUDE_MACHINE_ID:-}"
prompt CLAUDE_MACHINE_ID "Machine ID (hostname or custom label)" "$(hostname)"

CATALOG_FILE="$REPO_DIR/machine-catalog.md"
TOOL_ROWS=""
for tool in git node npm python3 docker gh pandoc curl wget jq make; do
  info="$(cmd_info "$tool")"
  if [[ "$info" == "not found" ]]; then
    TOOL_ROWS+="| \`${tool}\` | — | not found |\n"
  else
    p="${info%% |*}"; v="${info##*| }"
    TOOL_ROWS+="| \`${tool}\` | ${p} | ${v} |\n"
  fi
done

CC_VARIANT="vanilla"
if command -v claude &>/dev/null; then
  [[ "$(command -v claude)" == *mirror* ]] && CC_VARIANT="cc-mirror"
fi

cat > "$CATALOG_FILE" <<EOF
# Machine Catalog: ${CLAUDE_MACHINE_ID}

Platform: ${PLATFORM}
Last updated: ${DATE}

## Installed Tools

| Tool | Path | Version |
|------|------|---------|
$(printf "%b" "$TOOL_ROWS")

## Claude Code

- Variant: ${CC_VARIANT}
- Config path: ${CLAUDE_DIR}/

## MCP Servers

(none configured yet)
EOF

ok "Wrote machine-catalog.md (machine: ${CLAUDE_MACHINE_ID})"

# ---------------------------------------------------------------------------
# Step 5 — Symlinks
# ---------------------------------------------------------------------------
step "5/6" "Creating symlinks in ${CLAUDE_DIR}"

if [[ -f "$REPO_DIR/global/CLAUDE.md" ]]; then
  backup_if_exists "$CLAUDE_DIR/CLAUDE.md"
  ln -s "$REPO_DIR/global/CLAUDE.md" "$CLAUDE_DIR/CLAUDE.md"
  ok "Linked CLAUDE.md"
else
  warn "global/CLAUDE.md not found — skipping"
fi

for dir in foundation domains reference; do
  src="$REPO_DIR/global/$dir"
  dst="$CLAUDE_DIR/$dir"
  if [[ -d "$src" ]]; then
    backup_if_exists "$dst"
    ln -s "$src" "$dst"
    ok "Linked $dir/"
  else
    warn "global/$dir/ not found — skipping"
  fi
done

# ---------------------------------------------------------------------------
# Step 6 — Hooks
# ---------------------------------------------------------------------------
step "6/6" "Installing hooks"

HOOKS_SRC="$REPO_DIR/global/hooks"
if [[ -d "$HOOKS_SRC" ]]; then
  shopt -s nullglob
  hooks=("$HOOKS_SRC"/*.sh)
  shopt -u nullglob
  if [[ ${#hooks[@]} -gt 0 ]]; then
    for hook in "${hooks[@]}"; do
      fname="$(basename "$hook")"
      cp "$hook" "$CLAUDE_DIR/hooks/$fname"
      chmod +x "$CLAUDE_DIR/hooks/$fname"
      ok "Installed hook: $fname"
    done
  else
    warn "No .sh hooks found in global/hooks/"
  fi
else
  warn "global/hooks/ not found — skipping"
fi

# ---------------------------------------------------------------------------
# Optional — GitHub MCP
# ---------------------------------------------------------------------------
echo ""
do_mcp=false
if [[ "$NON_INTERACTIVE" == true ]]; then
  [[ -n "${CLAUDE_GITHUB_PAT:-}" ]] && do_mcp=true
else
  read -r -p "  Configure GitHub MCP server? [y/N]: " _mcp
  [[ "${_mcp,,}" == "y" ]] && do_mcp=true
fi

if [[ "$do_mcp" == true ]]; then
  CLAUDE_GITHUB_PAT="${CLAUDE_GITHUB_PAT:-}"
  if [[ "$NON_INTERACTIVE" == false ]]; then
    read -r -s -p "  GitHub PAT (hidden): " CLAUDE_GITHUB_PAT
    echo ""
  fi
  if [[ -n "$CLAUDE_GITHUB_PAT" ]]; then
    MCP_FILE="$CLAUDE_DIR/.mcp.json"
    backup_if_exists "$MCP_FILE"
    cat > "$MCP_FILE" <<EOF
{
  "mcpServers": {
    "github": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "${CLAUDE_GITHUB_PAT}"
      }
    }
  }
}
EOF
    ok "Wrote ~/.claude/.mcp.json (GitHub MCP)"
    sed -i 's/(none configured yet)/github (via @modelcontextprotocol\/server-github)/' "$CATALOG_FILE"
  else
    warn "No PAT provided — skipping MCP config"
  fi
fi

# ---------------------------------------------------------------------------
# Create first-run marker
# ---------------------------------------------------------------------------
touch "$REPO_DIR/.setup-pending"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}${GREEN}Setup complete.${RESET}"
echo ""
printf "${BOLD}%-20s${RESET} %s\n" "Platform:"    "$PLATFORM"
printf "${BOLD}%-20s${RESET} %s\n" "Machine ID:"  "$CLAUDE_MACHINE_ID"
printf "${BOLD}%-20s${RESET} %s\n" "Config dir:"  "$CLAUDE_DIR"
printf "${BOLD}%-20s${RESET} %s\n" "Repo root:"   "$REPO_DIR"
echo ""
echo -e "${BOLD}Symlinks in ${CLAUDE_DIR}:${RESET}"
echo "  CLAUDE.md   ->  global/CLAUDE.md"
echo "  foundation/ ->  global/foundation/"
echo "  domains/    ->  global/domains/"
echo "  reference/  ->  global/reference/"

# ---------------------------------------------------------------------------
# Offer interactive refinement
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}${BLUE}Interactive setup${RESET}"
echo "  Claude can now help you personalize your configuration:"
echo "  - Refine your user profile with real preferences"
echo "  - Choose which knowledge domains to enable"
echo "  - Set up your first project"
echo "  - Add global rules (e.g. 'always use bun', 'never auto-commit')"
echo ""

# Detect available Claude command
CLAUDE_CMD=""
if command -v mclaude &>/dev/null; then
  CLAUDE_CMD="mclaude"
elif command -v claude &>/dev/null; then
  CLAUDE_CMD="claude"
fi

if [[ -n "$CLAUDE_CMD" ]]; then
  do_refine=false
  if [[ "$NON_INTERACTIVE" == true ]]; then
    echo "  Run '$CLAUDE_CMD' in $REPO_DIR to start interactive setup."
  else
    read -r -p "  Launch Claude now for interactive setup? [Y/n]: " _refine
    [[ "${_refine,,}" != "n" ]] && do_refine=true
  fi

  if [[ "$do_refine" == true ]]; then
    echo ""
    echo -e "${BOLD}Launching $CLAUDE_CMD in ${REPO_DIR}...${RESET}"
    echo ""
    cd "$REPO_DIR"
    exec "$CLAUDE_CMD"
  fi
else
  echo -e "  ${YELLOW}Claude Code not found in PATH.${RESET}"
  echo "  After installing Claude Code, run it in ${REPO_DIR} to start interactive setup."
fi

echo ""
echo -e "${BOLD}Manual setup:${RESET}"
echo "  1. cd $REPO_DIR"
echo "  2. Run: claude  (or mclaude)"
echo "  Claude will detect the pending setup and guide you through it."
